package_update: true
package_upgrade: true

timezone: Europe/Berlin

manage_etc_hosts: true

packages:
  - docker.io
  - curl
  - git
  - btop

write_files:
  - path: /etc/netplan/01-netplan.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            nameservers:
              addresses:
                - 1.1.1.1
                - 1.0.0.1
    permissions: "0600"

runcmd:
  - netplan apply
  - sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
  - echo "PermitRootLogin prohibit-password" >> /etc/ssh/sshd_config
  - systemctl restart sshd
  - apt update
  - apt upgrade -y --allow-downgrades --allow-remove-essential --allow-change-held-packages
  - reboot
